# Generated by Django 6.0.8 on 2026-08-30 18:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_create_resources_and_permissions'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='Meet Lala', max_length=80)),
                ('headline', models.CharField(default='Real estate should feel more understandable.', max_length=180)),
                ('introduction', models.TextField(default='Lala Land Properties was created to make the journey toward homeownership feel less overwhelming and more understandable.', max_length=700)),
                ('portrait_alt_text', models.CharField(blank=True, max_length=250)),
                ('story', wagtail.fields.RichTextField(default='<p>Hi, I’m Lala. I help buyers understand their options, discover properties that suit their needs, and move forward with confidence.</p>')),
                ('philosophy_quote', models.CharField(default='Guidance, not pressure.', max_length=240)),
                ('approach', wagtail.fields.RichTextField(default='<p>Every buyer has different needs, priorities, and goals. Clear information, realistic expectations, and personalized service come first.</p>')),
                ('community', wagtail.fields.RichTextField(default='<p>With local knowledge of Negros Occidental, Lala Land helps people explore communities and properties with context—not just sales listings.</p>')),
                ('affiliation', models.CharField(default='Proudly affiliated with PRES Realty', max_length=160)),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_portraits', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
