# Generated by Django 6.0.8 on 2026-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0005_rename_content_admin_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('messenger_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'social contact settings',
                'verbose_name_plural': 'social contact settings',
            },
        ),
    ]
