# Generated by Django 6.0.8 on 2026-09-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0007_create_contact_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactsettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
