# Generated by Django 6.0.8 on 2026-09-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0008_sitecontactsettings_tiktok_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontactsettings',
            options={'verbose_name': 'contact page settings', 'verbose_name_plural': 'contact page settings'},
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='affiliation',
            field=models.CharField(default='Proudly affiliated with PRES Realty', max_length=160),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='exploring_text',
            field=models.TextField(default='Share what you know so far. It is completely fine if you are still exploring.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='hero_emphasis',
            field=models.CharField(default='looking for.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='hero_eyebrow',
            field=models.CharField(default='Contact Lala', max_length=80),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='hero_heading',
            field=models.TextField(default='Tell me what\nyou’re', max_length=140),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='hero_intro',
            field=models.TextField(default='No pressure and no complicated form. Share what matters to you, and we’ll begin with a clear conversation.', max_length=400),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='panel_emphasis',
            field=models.CharField(default='next place.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='panel_heading',
            field=models.TextField(default='Let’s find your', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='public_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='response_expectation',
            field=models.CharField(default='We’ll respond as soon as possible during business hours.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='service_area',
            field=models.CharField(default='Serving Negros Occidental', max_length=120),
        ),
    ]
