# Generated by Django 6.0.8 on 2026-09-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0009_alter_sitecontactsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactsettings',
            name='inquiry_notification_email',
            field=models.EmailField(blank=True, help_text='Private recipient for new inquiry alerts. Leave blank to disable email alerts.', max_length=254),
        ),
    ]
