# Generated by Django 6.0.8 on 2026-09-09 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0002_alter_inquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_type', models.CharField(blank=True, max_length=120)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_notification', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
