# Generated by Django 6.0.8 on 2026-08-29 21:52

import django.db.models.deletion
import django.db.models.functions.text
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(default='PH', max_length=2)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('city_municipality', models.CharField(max_length=120)),
                ('barangay', models.CharField(blank=True, max_length=120)),
                ('subdivision_area', models.CharField(blank=True, max_length=180)),
                ('street_address_private', models.TextField(blank=True)),
                ('latitude_private', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_private', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('public_label', models.CharField(max_length=220)),
                ('visibility', models.CharField(choices=[('EXACT', 'Exact public pin'), ('APPROXIMATE', 'Approximate public pin'), ('AREA_ONLY', 'Area label only'), ('HIDDEN', 'Hidden')], default='AREA_ONLY', max_length=16)),
                ('public_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('public_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['province', 'city_municipality', 'public_label'],
                'indexes': [models.Index(fields=['province', 'city_municipality', 'barangay'], name='properties__provinc_6093ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('development_type', models.CharField(choices=[('SUBDIVISION', 'Subdivision'), ('CONDOMINIUM', 'Condominium'), ('COMMERCIAL', 'Commercial'), ('MEMORIAL_PARK', 'Memorial park'), ('MIXED_USE', 'Mixed use'), ('OTHER', 'Other')], max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('description', wagtail.fields.RichTextField()),
                ('developer_name', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developments', to='properties.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('applicable_fields', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='properties_type_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('description', wagtail.fields.RichTextField()),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('memorial_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='properties.development')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='properties.propertytype')),
            ],
            options={
                'ordering': ['development', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(max_length=80, unique=True)),
                ('unit_or_lot_number_private', models.CharField(blank=True, max_length=120)),
                ('title_override', models.CharField(blank=True, max_length=180)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('furnishing', models.CharField(blank=True, choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI_FURNISHED', 'Semi-furnished'), ('FURNISHED', 'Furnished')], max_length=20)),
                ('occupancy_status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('OWNER_OCCUPIED', 'Owner occupied'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('inventory_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('UNDER_OFFER', 'Under offer'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.development')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.location')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.variant')),
            ],
            options={
                'ordering': ['reference_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('development', 'slug'), name='properties_variant_development_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('development'), name='properties_variant_development_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms__isnull', True), ('bathrooms__gte', 0), _connector='OR'), name='properties_variant_bathrooms_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('floor_area_sqm__isnull', True), ('floor_area_sqm__gt', 0), _connector='OR'), name='properties_variant_floor_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('lot_area_sqm__isnull', True), ('lot_area_sqm__gt', 0), _connector='OR'), name='properties_variant_lot_area_positive'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'inventory_status'], name='properties__propert_83be37_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms', 'lot_area_sqm'], name='properties__bedroom_ff5be1_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('variant__isnull', True), ('development__isnull', False), _connector='OR'), name='properties_property_variant_requires_development'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms__isnull', True), ('bathrooms__gte', 0), _connector='OR'), name='properties_property_bathrooms_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('floor_area_sqm__isnull', True), ('floor_area_sqm__gt', 0), _connector='OR'), name='properties_property_floor_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('lot_area_sqm__isnull', True), ('lot_area_sqm__gt', 0), _connector='OR'), name='properties_property_lot_area_positive'),
        ),
    ]
