# Generated by Django 6.0.8 on 2026-08-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_seed_property_types'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude_private__isnull', True), ('longitude_private__isnull', True)), models.Q(('latitude_private__isnull', False), ('longitude_private__isnull', False)), _connector='OR'), name='properties_location_private_coordinates_pair'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('public_latitude__isnull', True), ('public_longitude__isnull', True)), models.Q(('public_latitude__isnull', False), ('public_longitude__isnull', False)), _connector='OR'), name='properties_location_public_coordinates_pair'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('latitude_private__isnull', True), models.Q(('latitude_private__gte', -90), ('latitude_private__lte', 90)), _connector='OR'), name='properties_location_private_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('longitude_private__isnull', True), models.Q(('longitude_private__gte', -180), ('longitude_private__lte', 180)), _connector='OR'), name='properties_location_private_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('public_latitude__isnull', True), models.Q(('public_latitude__gte', -90), ('public_latitude__lte', 90)), _connector='OR'), name='properties_location_public_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('public_longitude__isnull', True), models.Q(('public_longitude__gte', -180), ('public_longitude__lte', 180)), _connector='OR'), name='properties_location_public_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('visibility__in', ['EXACT', 'APPROXIMATE']), _negated=True), models.Q(('public_latitude__isnull', False), ('public_longitude__isnull', False)), _connector='OR'), name='properties_location_public_pin_coordinates_required'),
        ),
    ]
