# Generated by Django 6.0.8 on 2026-09-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_normalize_psgc_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['reference_code'], 'verbose_name_plural': 'properties'},
        ),
    ]
