# Generated by Django 6.0.8 on 2026-09-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['development', 'name'], 'verbose_name': 'house model', 'verbose_name_plural': 'house models'},
        ),
    ]
