# Generated by Django 6.0.8 on 2026-08-29 23:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_title_snapshot', models.CharField(blank=True, max_length=180)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('interest', models.CharField(choices=[('FIRST_HOME', 'My first home'), ('FAMILY_HOME', 'A family home'), ('INVESTMENT', 'An investment property'), ('LOT', 'A lot'), ('COMMERCIAL', 'A commercial property'), ('RENTAL', 'A rental'), ('EXPLORING', 'I’m still exploring'), ('SPECIFIC', 'A specific property')], max_length=20)),
                ('preferred_location', models.CharField(blank=True, max_length=160)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('VIEWING', 'Viewing arranged'), ('CLOSED_WON', 'Closed — successful'), ('CLOSED_LOST', 'Closed — not proceeding'), ('SPAM', 'Spam'), ('ARCHIVED', 'Archived')], default='NEW', max_length=16)),
                ('consent_given_at', models.DateTimeField()),
                ('privacy_notice_version', models.CharField(default='placeholder-v1', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('NOTE', 'Internal note'), ('CALL', 'Call'), ('EMAIL', 'Email'), ('MESSAGE', 'Message'), ('VIEWING', 'Viewing')], default='NOTE', max_length=12)),
                ('body', models.TextField(max_length=3000)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_notes', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'assigned_to', 'created_at'], name='inquiries_i_status_3815a9_idx'),
        ),
    ]
