# Generated by Django 6.0.8 on 2026-08-29 22:32

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_location_properties_location_private_coordinates_pair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.CharField(max_length=300)),
                ('description', wagtail.fields.RichTextField()),
                ('inventory_mode', models.CharField(choices=[('SINGLE', 'Single property'), ('POOLED', 'Pooled variant inventory')], max_length=10)),
                ('available_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('public_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=16)),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.property')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.variant')),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('SALE', 'For sale'), ('RENT', 'For rent')], max_length=8)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('price_display', models.CharField(choices=[('EXACT', 'Exact price'), ('STARTING_AT', 'Starting at'), ('RANGE', 'Price range'), ('NEGOTIABLE', 'Negotiable'), ('CONTACT', 'Contact for price')], max_length=16)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rent_period', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=8)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_lease_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reservation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.listing')),
            ],
            options={
                'ordering': ['-active', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['workflow_status', 'public_status', 'published_at'], name='listings_li_workflo_17645f_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('variant__isnull', True)), models.Q(('property__isnull', True), ('variant__isnull', False)), _connector='OR'), name='listings_listing_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('available_quantity__isnull', True), ('inventory_mode', 'SINGLE'), ('property__isnull', False), ('variant__isnull', True)), models.Q(('available_quantity__isnull', False), ('inventory_mode', 'POOLED'), ('property__isnull', True), ('variant__isnull', False)), _connector='OR'), name='listings_listing_inventory_mode_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('listing',), name='listings_offer_one_active_per_listing'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('price_min__isnull', True), ('price_min__gt', 0), _connector='OR'), name='listings_offer_price_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('price_max__isnull', True), ('price_max__gt', 0), _connector='OR'), name='listings_offer_price_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('price_max__isnull', True), ('price_min__isnull', True), ('price_max__gte', models.F('price_min')), _connector='OR'), name='listings_offer_price_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__isnull', True), ('deposit_amount__gte', 0), _connector='OR'), name='listings_offer_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_fee__isnull', True), ('reservation_fee__gte', 0), _connector='OR'), name='listings_offer_reservation_fee_nonnegative'),
        ),
    ]
