# Generated by Django 6.0.8 on 2026-09-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-active', '-created_at'], 'verbose_name': 'price and availability', 'verbose_name_plural': 'prices and availability'},
        ),
    ]
