# Generated by Django 6.0.8 on 2026-09-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='final_cta_emphasis',
            field=models.CharField(default='feels like yours?', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_eyebrow',
            field=models.CharField(default='Begin your search', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_heading',
            field=models.TextField(default='Ready to find what', max_length=140),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_label',
            field=models.CharField(default='Let’s find your next home', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_emphasis',
            field=models.CharField(default='home.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(default='Real estate guidance for Negros Occidental', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.TextField(default='Find a place\nto call', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro',
            field=models.TextField(default='Navigate your real estate journey with honest guidance, local knowledge, and service shaped around you.', max_length=400),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta',
            field=models.CharField(default='Explore properties', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta',
            field=models.CharField(default='Let’s talk', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_body',
            field=models.TextField(default='Whether you are searching for your first home, exploring an investment, or simply learning your options, Lala Land helps make every next step feel clearer.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_cta',
            field=models.CharField(default='Tell me what you’re looking for', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_emphasis',
            field=models.CharField(default='starts here.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_eyebrow',
            field=models.CharField(default='A thoughtful way forward', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_heading',
            field=models.TextField(default='Your next chapter', max_length=140),
        ),
        migrations.AddField(
            model_name='homepage',
            name='resources_cta',
            field=models.CharField(default='Explore all resources', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='resources_emphasis',
            field=models.CharField(default='make your move.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='resources_eyebrow',
            field=models.CharField(default='Homebuyer resources', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='resources_heading',
            field=models.TextField(default='Learn before you', max_length=140),
        ),
    ]
