# Generated by Django 6.0.8 on 2026-08-29 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_location_properties_location_private_coordinates_pair_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('EXACT_LOCATION', 'Exact location'), ('PHONE_NUMBER', 'Customer phone numbers')], max_length=24)),
                ('reason', models.CharField(max_length=500)),
                ('requested_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='properties.location')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_access_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_access_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('EXACT_LOCATION', 'Exact location'), ('PHONE_NUMBER', 'Customer phone numbers')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_access_grants_issued', to=settings.AUTH_USER_MODEL)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_access_grants', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='properties.location')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_access_grants_revoked', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='access_requests.sensitiveaccessrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grantee', 'scope', 'expires_at'], name='access_requ_grantee_c0acc9_idx')],
            },
        ),
    ]
