# Generated by Django 6.0.8 on 2026-08-29 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0002_auditevent_immutable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('change_summary', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_revisions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity_type', 'entity_id', '-revision_number'],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'revision_number'), name='audittrail_catalog_revision_number_unique')],
            },
        ),
    ]
