# Generated by Django 6.0.8 on 2026-08-29 23:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_location_properties_location_private_coordinates_pair_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alt_text', models.CharField(help_text='Describe what is visible for visitors using screen readers.', max_length=250)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='properties.development')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_placements', to='wagtailimages.image')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='properties.property')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='properties.variant')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('development__isnull', True), ('property__isnull', False), ('variant__isnull', True)), models.Q(('development__isnull', True), ('property__isnull', True), ('variant__isnull', False)), models.Q(('development__isnull', False), ('property__isnull', True), ('variant__isnull', True)), _connector='OR'), name='media_catalogue_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_cover', True), ('property__isnull', False)), fields=('property',), name='media_catalogue_one_property_cover'), models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_cover', True), ('variant__isnull', False)), fields=('variant',), name='media_catalogue_one_variant_cover'), models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('development__isnull', False), ('is_cover', True)), fields=('development',), name='media_catalogue_one_development_cover')],
            },
        ),
    ]
