# Generated by Django 6.0.8 on 2026-09-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguemedia',
            name='kind',
            field=models.CharField(choices=[('PHOTO', 'Property photo'), ('FLOOR_PLAN', 'Floor plan')], default='PHOTO', max_length=16),
        ),
    ]
